---
title: "flat_detect_chars_structure.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# detect_chars_structure

```{r function-detect_chars_structure}
#' Detect character structure
#' Detect if values within a character variable match at least one of defined patterns
#'
#' @param vector Character. Input vector to detect pattern from
#' @param patterns Character. Patterns to detect within vector. Regex is supported
#' @param verbose Logical 1L. If TRUE, additional details related to the pattern detection are provided
#' @return Logical 1L. If verbose is set to TRUE, the function returns a list with the following elements in order: 
#'    - "Any defined structure" : Logical 1L. TRUE if the pattern is detected anywhere from the input vector
#'    - "Which" : Character. Unique values of input vector matching the defined patterns
#'    - "Where" : Integer. Indexes of values from input vector matching the defined patterns
#' @export
#'
detect_chars_structure <- function (vector, patterns, verbose = FALSE) {
  
  if (isFALSE(is.character(vector))) {
    stop("vector must be of type character")
  }
  
  uniques <- stats::na.omit(unique(as.character(vector)))
  detect <- stringr::str_detect(uniques, paste0(patterns, collapse = "|"))
  check <- isTRUE(any(detect))
  
  if (isFALSE(verbose)) {
    check
  } else {
    
    which <- unique(uniques[detect])
    where <- which(vector %in% which)
    
    list("Any defined structure" = check, 
         "Which" = which, 
         "Where" = where)
  }
}
```

```{r examples-detect_chars_structure}
detect_chars_structure(
  vector = c("ABCD1234", "4567EF", "89GHIJ10"), 
  patterns = "[:alpha:]{4}" # detect four consecutive alphabetic values
)

detect_chars_structure(
  vector = c("ABCD1234", "4567EF", "89GHIJ10"), 
  patterns = "[:alpha:]{4}", 
  verbose = TRUE
)
```

```{r tests-detect_chars_structure}
test_that("Valid outputs are consistent", {
  expect_true(detect_chars_structure(
  vector = c("ABCD1234", "4567EF", "89GHIJ10"), 
  patterns = "[:alpha:]{4}"))
  
  expect_equal(
    detect_chars_structure(
      vector = c("ABCD1234", "4567EF", "89GHIJ10"), 
      patterns = "[:alpha:]{4}", 
    verbose = TRUE),
    list(`Any defined structure` = TRUE, Which = c("ABCD1234", "89GHIJ10"
    ), Where = c(1L, 3L))
  )})

test_that("Errors are consistent", {
  
  expect_error(
    detect_chars_structure(
      vector = c(1:4), 
      patterns = "[:digit:]{1}"),
    regexp = "vector must be of type character")
})
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_detect_chars_structure.Rmd", vignette_name = NA)
```

