---
title: "flat_dupl_show.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# dupl_show

```{r function-dupl_show}
#' Show observations of all duplicated values of a variable or a combination of variables
#' @param data_frame Data.frame. Input data frame. Must be in the Global Environment and has a data.frame class
#' @param vars Character. Vector of variable or combination of variables
#' from which duplicates are checked
#' @return Data.frame. The part of inputted data frame with all observations of duplicated values of
#' indicated variable or combination of variables
#' @importFrom magrittr %>%
#' @export
#'
dupl_show <- function (data_frame, vars) {

  requireNamespace("magrittr")
  # Insert element-wise combination of vars input components within the data:
  # idvarsdupl
  data <- dplyr::mutate(data_frame,
                        idvarsdupl =
                          do.call(what = paste,
                                  purrr::map(vars, function (x)
                                    data_frame[[x]])))

  # Filter rows with values of idvarsdupl that appears
  # at least for the second time:
  data %>% dplyr::filter(duplicated(idvarsdupl)) %>%

    # extract idvarsdupl variable from the filtered data:
    dplyr::pull(idvarsdupl) %>%

    # extract all corresponding observations from data input:
    (function (p) dplyr::filter(data, idvarsdupl %in% p)) %>%

    # arrange values to visualize the duplicated cases:
    dplyr::arrange(!!dplyr::sym("idvarsdupl")) %>%

    # put vars input to first variable(s) location(s):
    dplyr::relocate(dplyr::all_of(vars)) %>%

    # remove idvarsdupl:
    dplyr::select(- !!dplyr::sym("idvarsdupl"))
}
```

```{r examples-dupl_show}
# A fictional data with duplicated values:
df <- data.frame("person_id" = c(1, 1, 2, 3,
                                 2, 4, 5, 5 ,1),
                 "person_age" = c(25, 25, 21, 32,
                                  21, 48, 50, 50, 52),
                 "survey_month" = c("jan", "feb", "mar", "apr",
                                    "apr", "may", "jun", "jul", "jan"),
                 "survey_answer" = c("no", "yes", "no", "yes",
                                     "yes", "yes", "no", "yes", NA))

# Shuffling observations and columns to make duplicates difficult to see:
set.seed(1)
df <- df[sample(1:nrow(df)),
         sample(1:ncol(df))]
df

# See all of the rows where person_id has more than an unique possible value: 
dupl_show(data = df, var = "person_id")

# See all of the rows where the combination of person_id and survey_month variables has 
# more than an unique possible value : 
dupl_show(data = df, var = c("person_id", "survey_month"))
```

```{r tests-dupl_show}
test_that("Valid outputs are consistent", {
  
  # A fictional data with duplicated values:
  df <- data.frame("person_id" = c(1, 1, 2, 3,
                                   2, 4, 5, 5 ,1),
                   "person_age" = c(25, 25, 21, 32,
                                    21, 48, 50, 50, 52),
                   "survey_month" = c("jan", "feb", "mar", "apr",
                                      "apr", "may", "jun", "jul", "jan"),
                   "survey_answer" = c("no", "yes", "no", "yes",
                                       "yes", "yes", "no", "yes", NA))
  
  # Shuffling observations and columns to make duplicates difficult to see:
  set.seed(1)
  df <- df[sample(1:nrow(df)),
           sample(1:ncol(df))]
  
  expect_equal(
    object = dupl_show(df, "person_id"),
    expected = structure(
      list(
        person_id = c(1, 1, 1, 2, 2, 5, 5), 
        survey_month = c("feb", "jan", "jan", "mar", "apr", "jun", "jul"), 
        survey_answer = c("yes", "no", NA, "no", "yes", "no", "yes"), 
        person_age = c(25, 25, 52, 21, 21, 50, 50)), 
      row.names = c(NA, -7L), 
      class = "data.frame"))
  
  expect_equal(
    object = dupl_show(df, c("person_id", "survey_month")),
    expected = structure(
      list(person_id = c(1, 1), 
           survey_month = c("jan", "jan"), 
           survey_answer = c("no", NA), 
           person_age = c(25, 52)), 
      row.names = c(NA, -2L), 
      class = "data.frame"))
})
```


# dupl_sources
    
```{r development-dupl_sources}
# You can prepare the code of the dupl_sources() function here
```
  
```{r function-dupl_sources}
#' Illustrate sources of all duplicated values of a variable or a combination of variables
#' @param data_frame Data.frame. Input data frame. Must be in the Global Environment and has a data.frame class
#' @param vars Character. Vector of variable or combination of variables
#' from which duplicates are checked
#' @param output_as_df Logical 1L. If TRUE, output is rendered as a data.frame. 
#' @return List or data.frame. For each duplicated row regarding to vars, different values of the same variable
#' are shown, separated by AND
#' @importFrom magrittr %>%
#' @export
#'
dupl_sources <- function (data_frame, vars, output_as_df = FALSE) {
  
  requireNamespace("magrittr")
  # Insert element-wise combination of vars input components within the data:
  # idvarsdupl
  data <- dplyr::mutate(data_frame,
                        idvarsdupl =
                          do.call(what = paste,
                                  purrr::map(vars, function (x)
                                    data_frame[[x]])))
  
  # Filter rows with values of idvarsdupl that appears
  # at least for the second time:
  data %>% dplyr::filter(duplicated(idvarsdupl)) %>%
    
    # extract idvarsdupl variable from the filtered data:
    dplyr::pull(idvarsdupl) %>%
    
    # extract all corresponding observations from data input:
    (function (p) dplyr::filter(data, idvarsdupl %in% p)) %>%
    
    # arrange values to visualize the duplicated cases:
    dplyr::arrange(!!dplyr::sym("idvarsdupl")) %>%
    
    # put vars input to first variable(s) location(s):
    dplyr::relocate(dplyr::all_of(vars)) %>%
    
    (\(d) dplyr::group_by(d, !!dplyr::sym("idvarsdupl")) %>%
       dplyr::summarise_all(\(x) stats::na.omit(unique(x)) %>%
                              paste0(collapse = " [AND] ")) %>%
       dplyr::ungroup() %>%
       apply(1, \(x) c(paste0(x[[1]], collapse = " "),
                       x[stringr::str_detect(x, " \\[AND\\] ")]))) %>%
    purrr::map(as.data.frame) -> result_list
  
  # Make result_list visually comfortable: 
  result_list <- purrr::map(result_list, \(x) {
    
    rownames(x)[1] <- paste(vars, collapse = "-")
    colnames(x) <- "values"
    x
  }) %>% (\(r) {
    stats::setNames(
      r, 
      purrr::map(
        r, 
        \(xr) xr[[1]][1] %>% 
          (\(xr2) glue::glue("Duplicate sources where {paste0(vars, collapse = '-')} equals {xr2}"))))
  })
  
  # Data.frame version of the result: 
  result_df <- result_list %>% 
    purrr::map(t) %>% purrr::map(as.data.frame) %>% 
    purrr::list_rbind() %>% magrittr::set_rownames(NULL)
  
  if (isTRUE(output_as_df)) {
    return(result_df)
  } else return(result_list)
}
```

```{r example-dupl_sources}
# A fictional data with duplicated values:
df <- data.frame("person_id" = c(1, 1, 2, 3,
                                 2, 4, 5, 5 ,1),
                 "person_age" = c(25, 25, 21, 32,
                                  21, 48, 50, 50, 52),
                 "survey_month" = c("jan", "feb", "mar", "apr",
                                    "apr", "may", "jun", "jul", "jan"),
                 "survey_answer" = c("no", "yes", "no", "yes",
                                     "yes", "yes", "no", "yes", NA))

# Shuffling observations and columns to make duplicates difficult to see:
set.seed(1)
df <- df[sample(1:nrow(df)),
         sample(1:ncol(df))]
df

dupl_sources(data_frame = df, vars = "person_id")
dupl_sources(data_frame = df, vars = "person_id", output_as_df = TRUE)
```

```{r tests-dupl_sources}
test_that("Valid outputs are consistent", {
  
  # A fictional data with duplicated values:
  df <- data.frame("person_id" = c(1, 1, 2, 3,
                                   2, 4, 5, 5 ,1),
                   "person_age" = c(25, 25, 21, 32,
                                    21, 48, 50, 50, 52),
                   "survey_month" = c("jan", "feb", "mar", "apr",
                                      "apr", "may", "jun", "jul", "jan"),
                   "survey_answer" = c("no", "yes", "no", "yes",
                                       "yes", "yes", "no", "yes", NA))
  
  # Shuffling observations and columns to make duplicates difficult to see:
  set.seed(1)
  df <- df[sample(1:nrow(df)),
           sample(1:ncol(df))]
  
  expect_equal(
    object = dupl_sources(data_frame = df, vars = "person_id"), 
    expected = list(
      `Duplicate sources where person_id equals 1` = structure(
        list(values = c(
          "1", "feb [AND] jan", "yes [AND] no", "25 [AND] 52"
        )),
        row.names = c("person_id", "survey_month", "survey_answer", "person_age"),
        class = "data.frame"
      ),
      `Duplicate sources where person_id equals 2` = structure(
        list(values = c("2", "mar [AND] apr", "no [AND] yes")),
        row.names = c("person_id", "survey_month", "survey_answer"),
        class = "data.frame"
      ),
      `Duplicate sources where person_id equals 5` = structure(
        list(values = c("5", "jun [AND] jul", "no [AND] yes")),
        row.names = c("person_id", "survey_month", "survey_answer"),
        class = "data.frame"
      )
    )
  )
  
  expect_equal(
    object = dupl_sources(data_frame = df, vars = "person_id", output_as_df = TRUE), 
    expected = structure(
      list(
        person_id = c("1", "2", "5"),
        survey_month = c("feb [AND] jan", "mar [AND] apr", "jun [AND] jul"),
        survey_answer = c("yes [AND] no", "no [AND] yes", "no [AND] yes"),
        person_age = c("25 [AND] 52", NA, NA)
      ),
      row.names = c(NA, -3L),
      class = "data.frame"
    )
  )
  
  expect_equal(
    object = dupl_sources(data_frame = df, vars = c("person_id", "survey_month")), 
    expected = list(
      `Duplicate sources where person_id-survey_month equals 1 jan` = structure(
        list(values = "1 jan"), 
        row.names = "person_id-survey_month", class = "data.frame"),
      `Duplicate sources where person_id-survey_month equals 25 [AND] 52` = structure(
        list(values = "25 [AND] 52"),
        row.names = "person_id-survey_month",
        class = "data.frame"
      )
    )
  )
  
  expect_equal(
    object = dupl_sources(data_frame = df, vars = c("person_id", "survey_month"), 
                          output_as_df = TRUE),
    expected = structure(
      list(`person_id-survey_month` = c("1 jan", "25 [AND] 52")),
      row.names = c(NA, -2L),
      class = "data.frame"))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_dupl_show.Rmd", 
               vignette_name = NA)
```

