---
title: "flat_replace_multiple.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# replace_multiple

```{r function-replace_multiple}
# replace_multiple

#' Replace character vector values using a correspondence approach
#' @param input_vector Character vector on which replacements take place
#' @param replacements Named character vector: replacement correspondences
#' @param replace_all Logical. If TRUE, stringr::str_replace_all() is used
#' instead of stringr::str_replace()
#' @examples
#' @importFrom magrittr %>%
#' @export
#'
replace_multiple <- function (input_vector, replacements,
                              replace_all = FALSE) {

  if (isFALSE(is.character(input_vector))) {
    
    stop("input_vector must be a character vector")
  }
  
  if (isFALSE(is.character(replacements))) {
    
    stop("replacements must be a character vector")
  }
  
  # if replace_all == TRUE, use str_replace_all instead of str_replace:
  replace_function <- function (...) {

    if (replace_all) stringr::str_replace_all(...)
    else stringr::str_replace(...)

  }

  input <- names(replacements)

  if (length(unique(input)) != length(input)) {
    stop("Original values must be unique in the `replacements` argument.")
  }

  output <- unname(replacements)

  replace_table <- data.frame(
    input, output
  )

  # replacement process:
  dplyr::tibble(input_vector = input_vector,
                origin =
                  stringr::str_extract(input_vector,
                                       input %>% paste(collapse = "|"))) %>%
    dplyr::left_join(replace_table, by = c("origin" = "input")) %>%
    dplyr::mutate(destination = replace_function(input_vector, origin, output)) %>%
    dplyr::pull(destination)
}
```

```{r examples-replace_multiple}
input <- c("one-one", "two-two-one", "three-three-two")

replace_multiple(input,
                 replacements =
                   c("one" = "1", "two" = "2",
                     "three" = "3"))

replace_multiple(input,
                 replacements =
                   c("one" = "1", "two" = "2",
                     "three" = "3"),
                 replace_all = TRUE)
```

```{r tests-replace_multiple}
test_that("Valid outputs are consistent", {
  
  input <- c("one-one", "two-two-one", "three-three-two")
  
  expect_identical(
    object = replace_multiple(input,
                              replacements =
                                c("one" = "1", "two" = "2",
                                  "three" = "3")), 
    expected = c("1-one", "2-two-one", "3-three-two")
  )
  
  expect_identical(
    object = replace_multiple(input,
                 replacements =
                   c("one" = "1", "two" = "2",
                     "three" = "3"),
                 replace_all = TRUE), 
    expected = c("1-1", "2-2-one", "3-3-two")
  )
})

test_that("Errors are consistent", {
  
  expect_error(
    object = replace_multiple(input_vector = 1:2, 
                              replacements = c("A", "B")), 
    regexp = "input_vector must be a character vector"
  )
  
  expect_error(
    object = replace_multiple(input_vector = c("A", "B"), 
                              replacements = 1:2), 
    regexp = "replacements must be a character vector"
  )
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_replace_multiple.Rmd", vignette_name = NA)
```

