---
title: "flat_convert_r.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```


# mask_convert_r
    
```{r development-mask_convert_r}
# You can prepare the code of the mask_convert_r() function here
```
  
```{r function-mask_convert_r}
#' Create an excel mask compatible with the convert_r() function
#' @param output_path Folder path where the mask will be created
#' @param output_filename File name (with extension) of the mask
#' @export
#'
mask_convert_r <- function (output_path,
                            output_filename = "mask_convert_r.xlsx") {
  
  if (isFALSE(dir.exists(output_path))) {
    
    stop(glue::glue("{output_path} doesn't exist"))
  }
  
  mask <- data.frame(folder_path = NA,
                     file = NA,
                     converted_file = NA,
                     to_convert = NA)
  
  writexl::write_xlsx(mask,
                      path = file.path(output_path,
                                       output_filename))
}
```

```{r example-mask_convert_r}
library(readxl)

out_filename <- "mask_example.xlsx"

mask_convert_r(
  output_path = current_script_location(),
  output_filename = out_filename)

out_filepath <- file.path(current_script_location(), 
                          out_filename)

file.exists(out_filepath)

readxl::read_excel(
  path = out_filepath)

file.remove(out_filepath)
```
  
```{r tests-mask_convert_r}
test_that("Expected errors", {
  
  expect_error(
    object = mask_convert_r(
      output_path = current_script_location() %>% 
        paste0("_no_chance_to_exist")), 
    regexp = "doesn't exist"
  )
})

test_that("Conversion format attributes", {

  library(magrittr)
  library(rio)

  mask_convert_r("./", "my_mask.xlsx")
  
  expect_true(file.exists("./my_mask.xlsx"))
  
  file.remove("./my_mask.xlsx")
  
  expect_false(file.exists("./my_mask.xlsx"))

  mask_convert_r("./", "my_mask_again.xlsx")
  
  expect_true(file.exists("./my_mask_again.xlsx"))
  
  mask <- import("./my_mask_again.xlsx")
  
  expect_true("mask" %in% ls())
  
  file.remove("./my_mask_again.xlsx")
  
  expect_false(file.exists("./my_mask_again.xlsx"))
  
  expect_identical(class(mask), "data.frame")
  
  expect_identical(names(mask),
                   c("folder_path", "file",
                     "converted_file", "to_convert"))
})
```
  


# convert_r

```{r function-convert_r}
#' convert_r Title
#'
#' @return 1
#' @export
#'
#' @examples
convert_r <- function() {
  1
}
```

```{r examples-convert_r}
convert_r()
```

```{r tests-convert_r}
test_that("convert_r works", {
  expect_true(inherits(convert_r, "function"))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_convert_r.Rmd", vignette_name = "Go further")
```

