# WARNING - Generated by {fusen} from dev/flat_convert_all.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  
  # Not possible to test in background because the function needs RStudio: 
  expect_false(object = rstudioapi::isAvailable())
})

test_that("Errors are consistent", {
  
  mydir <- system.file("permadir_examples_and_tests/convert_all", package = "industtry")
  
  expect_error(convert_all(input_folderpath = "noexist"),
               regexp = "input_folderpath must be a valid path")
  
  expect_error(convert_all(input_folderpath = mydir, considered_extensions = 1),
               regexp = "considered_extensions must be a character vector")
  
  expect_error(convert_all(input_folderpath = mydir, 
                           considered_extensions = c("rds", "csv"),
                           to = 1),
               regexp = "to must be a 1L character vector")
  
  expect_error(convert_all(input_folderpath = mydir, 
                           considered_extensions = c("rds", "csv"),
                           to = "parquet", output_folderpath = "noexist"),
               regexp = "output_folderpath must be a valid path")
})
