# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

test_that("inspect_vars works", {
  
  mydir <- file.path(tempdir(), "inspect_vars_tests_examples")
  dir.create(mydir)
  
  library(magrittr)
  saveRDS(cars, file.path(mydir, "cars1.rds"))
  saveRDS(mtcars, file.path(mydir, "cars2.rds"))
  
  # Code below illustrates how to use the function:
  inspect_vars(input_path = mydir, output_path = mydir,
               output_label = "cardata", 
               considered_extensions = "rds")
  
  compared <- purrr::map(1:10, \(x)
                           rio::import(file.path(mydir, "inspect_vars_cardata.xlsx"),
                                       sheet = x)) %>%
    magrittr::set_names(c("dims", "inspect_tot", "inspect_cars1", "inspect_cars2",
                          "vars_detect", "vars_detect_everywhere", "vars_detect_not_everywhere",
                          "vars_compclasses", "vars_compclasses_allsame", "vars_compclasses_not_allsame"))
  
  comparison <- list(
    dims = structure(
      list(
        datasets = c("cars1", "cars2"),
        nobs = c(50, 32),
        nvar = c(2, 11)
      ),
      class = "data.frame",
      row.names = 1:2
    ),
    inspect_tot = structure(
      list(
        datasets = c(
          "cars1",
          "cars1",
          "cars2",
          "cars2",
          "cars2",
          "cars2",
          "cars2",
          "cars2",
          "cars2",
          "cars2",
          "cars2",
          "cars2",
          "cars2"
        ),
        nvar = c(2, 2, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11),
        nobs = c(50, 50, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32),
        variables = c(
          "speed",
          "dist",
          "mpg",
          "cyl",
          "disp",
          "hp",
          "drat",
          "wt",
          "qsec",
          "vs",
          "am",
          "gear",
          "carb"
        ),
        class = c(
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric"
        ),
        nb_distinct = c(
          "19",
          "35",
          "25",
          "3",
          "27",
          "22",
          "22",
          "29",
          "30",
          "2",
          "2",
          "3",
          "6"
        ),
        prop_distinct = c(
          "0.38",
          "0.7",
          "0.78125",
          "0.09375",
          "0.84375",
          "0.6875",
          "0.6875",
          "0.90625",
          "0.9375",
          "0.0625",
          "0.0625",
          "0.09375",
          "0.1875"
        ),
        nb_na = c("0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"),
        prop_na = c("0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"),
        nb_void = c("0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"),
        prop_void = c("0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"),
        nchars = c(
          "1 / 2",
          "1 / 2 / 3",
          "2 / 4",
          "1",
          "2 / 3 / 4 / 5",
          "2 / 3",
          "1 / 3 / 4",
          "3 / 4 / 5",
          "2 / 4 / 5",
          "1",
          "1",
          "1",
          "1"
        ),
        modalities = c(
          "4 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15",
          "2 / 4 / 10 / 14 / 16 / 17 / 18 / 20 / 22 / 24",
          "10.4 / 13.3 / 14.3 / 14.7 / 15 / 15.2 / 15.5 / 15.8 / 16.4 / 17.3",
          "4 / 6 / 8",
          "71.1 / 75.7 / 78.7 / 79 / 95.1 / 108 / 120.1 / 120.3 / 121 / 140.8",
          "52 / 62 / 65 / 66 / 91 / 93 / 95 / 97 / 105 / 109",
          "2.76 / 2.93 / 3 / 3.07 / 3.08 / 3.15 / 3.21 / 3.23 / 3.54 / 3.62",
          "1.513 / 1.615 / 1.835 / 1.935 / 2.14 / 2.2 / 2.32 / 2.465 / 2.62 / 2.77",
          "14.5 / 14.6 / 15.41 / 15.5 / 15.84 / 16.46 / 16.7 / 16.87 / 16.9 / 17.02",
          "0 / 1",
          "0 / 1",
          "3 / 4 / 5",
          "1 / 2 / 3 / 4 / 6 / 8"
        )
      ),
      class = "data.frame",
      row.names = c(NA, 13L)
    ),
    inspect_cars1 = structure(
      list(
        `1:nrow(i)` = c("Obs =", "Nvars =", "1", "2"),
        variables = c("50", "2", "speed", "dist"),
        class = c(NA, NA, "numeric", "numeric"),
        nb_distinct = c(NA, NA, "19", "35"),
        prop_distinct = c(NA, NA, "0.38", "0.7"),
        nb_na = c(NA, NA, "0", "0"),
        prop_na = c(NA, NA, "0", "0"),
        nb_void = c(NA, NA, "0", "0"),
        prop_void = c(NA, NA, "0", "0"),
        nchars = c(NA, NA, "1 / 2", "1 / 2 / 3"),
        modalities = c(
          NA,
          NA,
          "4 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15",
          "2 / 4 / 10 / 14 / 16 / 17 / 18 / 20 / 22 / 24"
        )
      ),
      class = "data.frame",
      row.names = c(NA, 4L)
    ),
    inspect_cars2 = structure(
      list(
        `1:nrow(i)` = c(
          "Obs =",
          "Nvars =",
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11"
        ),
        variables = c(
          "32",
          "11",
          "mpg",
          "cyl",
          "disp",
          "hp",
          "drat",
          "wt",
          "qsec",
          "vs",
          "am",
          "gear",
          "carb"
        ),
        class = c(
          NA,
          NA,
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric"
        ),
        nb_distinct = c(NA, NA, "25", "3", "27", "22", "22", "29", "30", "2", "2", "3", "6"),
        prop_distinct = c(
          NA,
          NA,
          "0.78125",
          "0.09375",
          "0.84375",
          "0.6875",
          "0.6875",
          "0.90625",
          "0.9375",
          "0.0625",
          "0.0625",
          "0.09375",
          "0.1875"
        ),
        nb_na = c(NA, NA, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"),
        prop_na = c(NA, NA, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"),
        nb_void = c(NA, NA, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"),
        prop_void = c(NA, NA, "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"),
        nchars = c(
          NA,
          NA,
          "2 / 4",
          "1",
          "2 / 3 / 4 / 5",
          "2 / 3",
          "1 / 3 / 4",
          "3 / 4 / 5",
          "2 / 4 / 5",
          "1",
          "1",
          "1",
          "1"
        ),
        modalities = c(
          NA,
          NA,
          "10.4 / 13.3 / 14.3 / 14.7 / 15 / 15.2 / 15.5 / 15.8 / 16.4 / 17.3",
          "4 / 6 / 8",
          "71.1 / 75.7 / 78.7 / 79 / 95.1 / 108 / 120.1 / 120.3 / 121 / 140.8",
          "52 / 62 / 65 / 66 / 91 / 93 / 95 / 97 / 105 / 109",
          "2.76 / 2.93 / 3 / 3.07 / 3.08 / 3.15 / 3.21 / 3.23 / 3.54 / 3.62",
          "1.513 / 1.615 / 1.835 / 1.935 / 2.14 / 2.2 / 2.32 / 2.465 / 2.62 / 2.77",
          "14.5 / 14.6 / 15.41 / 15.5 / 15.84 / 16.46 / 16.7 / 16.87 / 16.9 / 17.02",
          "0 / 1",
          "0 / 1",
          "3 / 4 / 5",
          "1 / 2 / 3 / 4 / 6 / 8"
        )
      ),
      class = "data.frame",
      row.names = c(NA, 13L)
    ),
    vars_detect = structure(
      list(
        vars_union = c(
          "speed",
          "dist",
          "mpg",
          "cyl",
          "disp",
          "hp",
          "drat",
          "wt",
          "qsec",
          "vs",
          "am",
          "gear",
          "carb"
        ),
        cars1.rds = c("ok", "ok", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"),
        cars2.rds = c(
          "-",
          "-",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok"
        )
      ),
      class = "data.frame",
      row.names = c(NA, 13L)
    ),
    vars_detect_everywhere = structure(
      list(
        vars_union = logical(0),
        cars1.rds = logical(0),
        cars2.rds = logical(0)
      ),
      class = "data.frame",
      row.names = character(0)
    ),
    vars_detect_not_everywhere = structure(
      list(
        vars_union = c(
          "speed",
          "dist",
          "mpg",
          "cyl",
          "disp",
          "hp",
          "drat",
          "wt",
          "qsec",
          "vs",
          "am",
          "gear",
          "carb"
        ),
        cars1.rds = c("ok", "ok", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"),
        cars2.rds = c(
          "-",
          "-",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok",
          "ok"
        )
      ),
      class = "data.frame",
      row.names = c(NA, 13L)
    ),
    vars_compclasses = structure(
      list(
        vars_union = c(
          "speed",
          "dist",
          "mpg",
          "cyl",
          "disp",
          "hp",
          "drat",
          "wt",
          "qsec",
          "vs",
          "am",
          "gear",
          "carb"
        ),
        cars1.rds = c(
          "numeric",
          "numeric",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-"
        ),
        cars2.rds = c(
          "-",
          "-",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric"
        )
      ),
      class = "data.frame",
      row.names = c(NA, 13L)
    ),
    vars_compclasses_allsame = structure(
      list(
        vars_union = c(
          "speed",
          "dist",
          "mpg",
          "cyl",
          "disp",
          "hp",
          "drat",
          "wt",
          "qsec",
          "vs",
          "am",
          "gear",
          "carb"
        ),
        cars1.rds = c(
          "numeric",
          "numeric",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          "-"
        ),
        cars2.rds = c(
          "-",
          "-",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric",
          "numeric"
        )
      ),
      class = "data.frame",
      row.names = c(NA, 13L)
    ),
    vars_compclasses_not_allsame = structure(
      list(
        vars_union = logical(0),
        cars1.rds = logical(0),
        cars2.rds = logical(0)
      ),
      class = "data.frame",
      row.names = character(0)
    )
  )
  
  expect_equivalent(
    object = comparison, expected = compared)
  
  unlink(mydir, recursive = TRUE)
})
