# WARNING - Generated by {fusen} from dev/flat_convert_r.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {

  library(magrittr)

  mydir <- system.file("permadir_examples_and_tests/convert_r", package = "industtry")

  # Create an artificial compatible mask with R:
  mask <- data.frame(
    "folder_path" = rep(mydir, 2),
    "file" = c("original_cars.rds", "original_mtcars.csv"),
    "converted_file" = c("converted_cars.parquet", "converted_mtcars.parquet"),
    "to_convert" = rep(1, 2)
  )
  writexl::write_xlsx(mask, file.path(mydir, "mask_convert_r_completed.xlsx"))

  expect_equal(list.files(mydir) %>%
                 purrr::keep(stringr::str_detect(., "mask\\_") &
                               stringr::str_detect(., "completed")),
               "mask_convert_r_completed.xlsx")

  # As it intended to run into main RStudio session, it's difficult to test
  # the convert_r() function in the R dev sense.
  # The following test will only pass in check but not on live dev in RStudio:
  expect_false(
    object = rstudioapi::isAvailable())

  # Remove completed mask for tests integrity:
  file.remove(file.path(mydir, "mask_convert_r_completed.xlsx"))
})
