# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  
  left_table <- data.frame("person_id" = c(1, 1, 2, 3,
                                           2, 4, 5, 5 ,1),
                           "person_age" = c(25, 25, 21, 32,
                                            21, 48, 50, 50, 52),
                           "survey_month" = c("jan", "feb", "mar", "apr",
                                              "apr", "may", "jun", "jul", "jan"),
                           "survey_answer" = c("no", "yes", "no", "yes",
                                               "yes", "yes", "no", "yes", NA))
  
  right_table <- data.frame("person_id" = c(2, 5, 4, 3, 1), 
                            "person_name" = c("John", "Marie", "Pierre", "Marc", "Jimmy"))
  
  expect_equal(ljoin_checks(left_table, right_table, by = "person_id"), 
               structure(
                 list(
                   person_id = c(1, 1, 2, 3, 2, 4, 5, 5, 1),
                   person_age = c(25, 25, 21, 32, 21, 48, 50, 50, 52),
                   survey_month = c("jan", "feb", "mar", "apr", "apr", "may", "jun", "jul", "jan"),
                   survey_answer = c("no", "yes", "no", "yes", "yes", "yes", "no", "yes", NA),
                   person_name = c(
                     "Jimmy",
                     "Jimmy",
                     "John",
                     "Marc",
                     "John",
                     "Pierre",
                     "Marie",
                     "Marie",
                     "Jimmy"
                   )
                 ),
                 class = "data.frame",
                 row.names = c(NA, -9L)
               ))
  
  expect_message(ljoin_checks(left_table, right_table, by = "person_id"), 
                 "person_id are common var names accross the two tables")
})
