# WARNING - Generated by {fusen} from dev/flat_importations.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  
  # This test will not pass within RStudio but will in checks: 
  expect_false(
    object = rstudioapi::isAvailable())
})

test_that("Errors are consistent", {
  
  mydir <- system.file("permadir_examples_and_tests/importations", package = "industtry")
  lfiles_nodupl_invalid <- c(list.files(mydir, full.names = TRUE), 
                             file.path(mydir, "novalid", "cars2.rds"))
  lfiles <- list.files(mydir, recursive = TRUE, full.names = TRUE)
  
  
  expect_error(
    object = parallel_import(lfiles), 
    regexp = "File names must be unique")
  
  expect_error(
    object = parallel_import(lfiles_nodupl_invalid), 
    regexp = "All file_paths must be valid")
})
