# WARNING - Generated by {fusen} from dev/flat_replace_multiple.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  
  input <- c("one-one", "two-two-one", "three-three-two")
  
  expect_identical(
    object = replace_multiple(input,
                              replacements =
                                c("one" = "1", "two" = "2",
                                  "three" = "3")), 
    expected = c("1-one", "2-two-one", "3-three-two")
  )
  
  expect_identical(
    object = replace_multiple(input,
                 replacements =
                   c("one" = "1", "two" = "2",
                     "three" = "3"),
                 replace_all = TRUE), 
    expected = c("1-1", "2-2-one", "3-3-two")
  )
})

test_that("Errors are consistent", {
  
  expect_error(
    object = replace_multiple(input_vector = 1:2, 
                              replacements = c("A", "B")), 
    regexp = "input_vector must be a character vector"
  )
  
  expect_error(
    object = replace_multiple(input_vector = c("A", "B"), 
                              replacements = 1:2), 
    regexp = "replacements must be a character vector"
  )
})
