# WARNING - Generated by {fusen} from dev/flat_importations.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {

  library(magrittr)
  mydir <- system.file("permadir_examples_and_tests/importations", package = "industtry")
  lfiles <- list.files(mydir, full.names = TRUE) %>% 
    (\(x) x[stringr::str_detect(x, "\\.rds$")])

  expect_equal(
    object = serial_import(lfiles), 
    expected = list(NULL, NULL))
})

test_that("Errors are consistent", {
  
  mydir <- system.file("permadir_examples_and_tests/importations", package = "industtry")
  lfiles_nodupl_invalid <- c(list.files(mydir, full.names = TRUE), 
                             file.path(mydir, "novalid", "cars2.rds"))
  lfiles <- list.files(mydir, recursive = TRUE, full.names = TRUE)
  
  expect_error(
    object = serial_import(lfiles), 
    regexp = "File names must be unique")
  
  expect_error(
    object = serial_import(lfiles_nodupl_invalid), 
    regexp = "All file_paths must be valid")
})
