# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

test_that("vars_compclasses works", {
  library(magrittr)
  data(cars)
  data(mtcars)
  
  expect_equal(
    object = vars_compclasses(c("cars", "mtcars")), 
    expected = structure(
      list(
        vars_union = c("speed", "dist", "mpg", "cyl", 
                       "disp", "hp", "drat", "wt", "qsec", "vs", "am", "gear", "carb"), 
        cars = c("numeric", "numeric", "-", "-", "-", "-", "-", "-", 
                 "-", "-", "-", "-", "-"), 
        mtcars = c("-", "-", "numeric", "numeric", 
                   "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", 
                   "numeric", "numeric", "numeric")), 
      row.names = c(NA, -13L), 
      class = "data.frame"))
})
