# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  
  library(magrittr)
  library(dplyr)
  data(cars)
  data(mtcars)

  vdetect_table <- vars_detect(c("cars", "mtcars"))
  
  expect_equal(
    object = vars_detect_everywhere(vdetect_table), 
    expected = structure(list(
      vars_union = character(0), 
      cars = character(0), 
      mtcars = character(0)), 
      row.names = integer(0), 
      class = "data.frame"))
})
