# WARNING - Generated by {fusen} from dev/flat_paths_and_files.Rmd: do not edit by hand

test_that("No exact test but RStudio should not be available in the tests", {
  
  expect_false(.Platform$GUI == "RStudio")
  
  expect_error(current_script_location())
})
