# WARNING - Generated by {fusen} from dev/flat_rename_r.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  
  library(magrittr)
  data(cars)
  data(mtcars)
  
  mydir <- tempfile()
  dir.create(mydir)
  
  saveRDS(cars, file.path(mydir, "cars.rds"))
  saveRDS(mtcars, file.path(mydir, "mtcars.rds"))
  
  expect_equal(list.files(mydir), 
               c("cars.rds", "mtcars.rds"))
  
  mask_rename_r(input_path = mydir)
  
  expect_equal(list.files(mydir), 
               c("cars.rds", "mask_rename_r.xlsx", "mtcars.rds"))
  
  expect_equal(
    readxl::read_xlsx(file.path(mydir, "mask_rename_r.xlsx")),
    structure(
      list(
        file = c("cars.rds", "mtcars.rds"),
        renamed_file = c(NA, NA),
        to_rename = c(NA, NA)
      ),
      class = c("tbl_df", "tbl", "data.frame"),
      row.names = c(NA, -2L)
    ))
  
  unlink(mydir, recursive = TRUE)
})
