# WARNING - Generated by {fusen} from dev/flat_inspect_variants.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  library(magrittr)
  data(cars)
  mydir <- tempdir()
  dir.create(mydir)
  inspect_write(data_frame_name = "cars", 
                output_path = mydir, 
                output_label = "cars")
  comparison <- readxl::read_xlsx(file.path(mydir, "inspect_cars.xlsx"))
  compared <- structure(list(
    `1:nrow(i)` = c("Obs =", "Nvars =", "1", "2"), 
    variables = c("50", "2", "speed", "dist"), 
    class = c(NA, NA, "numeric", "numeric"), 
    nb_distinct = c(NA, NA, "19", "35"), 
    prop_distinct = c(NA, NA, "0.38", "0.7"), 
    nb_na = c(NA, NA, "0", "0"), 
    prop_na = c(NA, NA, "0", "0"), 
    nb_void = c(NA, NA, "0", "0"), 
    prop_void = c(NA, NA, "0", "0"), 
    nchars = c(NA, NA, "1 / 2", "1 / 2 / 3"), 
    modalities = c(NA, NA, "4 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15", 
    "2 / 4 / 10 / 14 / 16 / 17 / 18 / 20 / 22 / 24")), 
    class = c("tbl_df", 
              "tbl", "data.frame"), 
    row.names = c(NA, -4L))

  expect_equal(object = comparison, expected = compared)
  
  unlink(mydir, recursive = TRUE)
})

test_that("Errors are consistent", {
  
  library(magrittr)
  data(cars)
  data(uspop)
  mydir <- tempdir()
  dir.create(mydir)
  
  expect_error(inspect_write(data_frame_name = "cars_noexist", 
                             output_path = mydir, output_label = "cars"))
  
  expect_error(inspect_write(data_frame_name = "cars", 
                             output_path = paste0(mydir, "noexist"), 
                             output_label = "cars"))
  
  expect_error(inspect_write(data_frame_name = "cars", 
                             output_path = paste0(mydir, "noexist"), 
                             output_label = "cars"))
  
  expect_error(inspect_write(data_frame_name = "uspop", 
                             output_path = mydir, 
                             output_label = "cars"))
  
  unlink(mydir, recursive = TRUE)
})
