# WARNING - Generated by {fusen} from dev/flat_dupl_show.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  
  # A fictional data with duplicated values:
  df <- data.frame("person_id" = c(1, 1, 2, 3,
                                   2, 4, 5, 5 ,1),
                   "person_age" = c(25, 25, 21, 32,
                                    21, 48, 50, 50, 52),
                   "survey_month" = c("jan", "feb", "mar", "apr",
                                      "apr", "may", "jun", "jul", "jan"),
                   "survey_answer" = c("no", "yes", "no", "yes",
                                       "yes", "yes", "no", "yes", NA))
  
  # Shuffling observations and columns to make duplicates difficult to see:
  set.seed(1)
  df <- df[sample(1:nrow(df)),
           sample(1:ncol(df))]
  
  expect_equal(
    object = dupl_show(df, "person_id"),
    expected = structure(
      list(
        person_id = c(1, 1, 1, 2, 2, 5, 5), 
        survey_month = c("feb", "jan", "jan", "mar", "apr", "jun", "jul"), 
        survey_answer = c("yes", "no", NA, "no", "yes", "no", "yes"), 
        person_age = c(25, 25, 52, 21, 21, 50, 50)), 
      row.names = c(NA, -7L), 
      class = "data.frame"))
  
  expect_equal(
    object = dupl_show(df, c("person_id", "survey_month")),
    expected = structure(
      list(person_id = c(1, 1), 
           survey_month = c("jan", "jan"), 
           survey_answer = c("no", NA), 
           person_age = c(25, 52)), 
      row.names = c(NA, -2L), 
      class = "data.frame"))
})
