# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  
  library(magrittr)
  data(cars)
  data(mtcars)
  
  expect_equal(
    object = vars_detect(c("cars", "mtcars")), 
    expected = structure(
      list(
        vars_union = c("speed", "dist", "mpg", "cyl", 
                       "disp", "hp", "drat", "wt", "qsec", "vs", "am", "gear", "carb"
        ), 
        cars = c("ok", "ok", "-", "-", "-", "-", "-", "-", "-", "-", 
                 "-", "-", "-"), 
        mtcars = c("-", "-", "ok", "ok", "ok", "ok", 
                   "ok", "ok", "ok", "ok", "ok", "ok", "ok")), 
      class = "data.frame", 
      row.names = c(NA, -13L)))
})
