# WARNING - Generated by {fusen} from dev/flat_paths_and_files.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
 
  pvector <- c(
    "level_1/level_2/level_3/file_1.ext", 
    "level_1/level_2/level_3/file_2.ext"
  )
  
  expect_identical(
    object = path_move(pvector, "/", 1),
    expected = c("level_1", "level_1")
  )
  
  expect_identical(
    object = path_move(pvector, "/", 2),
    expected = c("level_1/level_2", "level_1/level_2")
  )
  
  expect_identical(
    object = path_move(pvector, "/", 3),
    expected = c("level_1/level_2/level_3", 
                 "level_1/level_2/level_3")
  )
  
  expect_identical(
    object = path_move(pvector, "/", - 1), 
    expected = c("level_1/level_2/level_3", 
                 "level_1/level_2/level_3")
    )
  
  expect_identical(
    object = path_move(pvector, "/", - 2), 
    expected = c("level_1/level_2", 
                 "level_1/level_2")
    )
  
  expect_identical(
    object = path_move(pvector, "/", - 3), 
    expected = c("level_1", 
                 "level_1")
    )
  
})
