# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

test_that("Valid outputs are consistent", {
  
  library(magrittr)
  data(cars)
  data(mtcars)
  vdetect_table <- vars_detect(c("cars", "mtcars"))
  
  expect_equal(
    object = vars_detect_not_everywhere(vdetect_table), 
    expected = structure(
      list(
        vars_union = c("speed", "dist", "mpg", "cyl", 
                       "disp", "hp", "drat", "wt", "qsec", "vs", "am", "gear", "carb"), 
        cars = c("ok", "ok", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"), 
        mtcars = c("-", "-", "ok", "ok", "ok", "ok", 
                   "ok", "ok", "ok", "ok", "ok", "ok", "ok")), 
      row.names = c(NA, 13L), 
      class = "data.frame"))
})
