# WARNING - Generated by {fusen} from dev/flat_assign_to_global.Rmd: do not edit by hand

#' Assign to global environment
#'
#' @param name Character. Name to assign the object 
#' @param object Object to assign to the name
#' @param pos Integer 1L
#'
#' @return function. Assignment to global environment
#' @export
#' @source https://stackoverflow.com/questions/28180989/r-cmd-check-found-the-following-assignments-to-the-global-environment
#'
assign_to_global <- function(name, object, pos) {
  (function (name, object, pos)
    assign(name, object, envir = as.environment(pos)))(name, object, pos = 1L)
}
