# WARNING - Generated by {fusen} from dev/flat_convert_r.Rmd: do not edit by hand

#' Industrialized dataset formats conversion (RStudio only)
#' @param mask_filepath Character 1L. Entire file path of the excel mask
#' @param output_path Character 1L. Folder path where the converted datasets will be placed
#' @importFrom magrittr %>%
#' @export
#'
#' @examples
#' library(magrittr)
#'
#' mydir <- system.file("permadir_examples_and_tests/convert_r", package = "industtry")
#'
#' # Datasets to convert (one-shot):
#' # rio::export(cars, file.path(mydir, "original_cars.rds"))
#' # rio::export(mtcars, file.path(mydir, "original_mtcars.csv"))
#'
#' # Create an artificial compatible mask with R:
#' mask <- data.frame(
#'   "folder_path" = rep(mydir, 2),
#'   "file" = c("original_cars.rds", "original_mtcars.csv"),
#'   "converted_file" = c("converted_cars.parquet", "converted_mtcars.parquet"),
#'   "to_convert" = rep(1, 2)
#' )
#' writexl::write_xlsx(mask, file.path(mydir, "mask_convert_r.xlsx"))
#'
#' if (rstudioapi::isAvailable()) {
#'   convert_r(
#'     mask_filepath = file.path(mydir, "mask_convert_r.xlsx"),
#'     output_path = mydir)} else {
#'       message("You're not in RStudio. This example will not run.")
#'     }
#'
#' # See original and converted files:
#' list.files(mydir) %>% purrr::keep(stringr::str_detect(., "cars"))
#'
#' # Remove converted files for tests integrity:
#' file.remove(file.path(
#'   mydir,
#'   c("converted_cars.parquet", "converted_mtcars.parquet")))
convert_r <- function (mask_filepath, output_path) {

  requireNamespace("magrittr")

  if (isFALSE(file.exists(mask_filepath))) {

    stop("mask_filepath doesn't exist. It must be a valid and full path including the xlsx file.")
  }

  if (isFALSE(dir.exists(output_path))) {

    stop("output_path doesn't exist. Check path validity.")
  }

  # import mask:
  prm <- rio::import(mask_filepath)

  # filter only datasets to convert:
  prm <- dplyr::filter(prm, to_convert == 1)

  # indicate row number (technically useful):
  prm <- dplyr::mutate(prm, row_number = 1:nrow(prm))

  # transform imported mask of r rows into a list of r elements:
  sp <- split(prm, prm$row_number) %>%
    magrittr::set_names(paste0(prm$folder_path, "/", prm$file))

  # for each element of the list, run a job that
  # (1) import indicated datasets,
  # (2) for imported datasets, replace void character values with real NAs,
  # (3) eliminate eventual spaces in character values corners,
  # (4) export resulting dataset in output_path as indicated in the mask
  sp %>% (\(l) {
    purrr::map(names(l), \(x) {
      l <- l
      output_path <- output_path
      job::job({

        # library(magrittr) # causes a note.

        rio::import(file.path(l[[x]][["folder_path"]], l[[x]][["file"]])) %>%
          dplyr::mutate_all(\(y) {y[nchar(as.character(y)) == 0] <- NA ; y}) %>%
          dplyr::mutate_if(is.character, \(c) stringr::str_trim(c)) %>%
          rio::export(file.path(output_path, l[[x]][["converted_file"]]))
        job::export("none")
      }, title = x %>% strsplit("/") %>%
        purrr::map(\(xx) xx[length(xx)]) %>% unlist %>% 
        (\(u) paste("Conversion of ", u)))
    })
  })
}
