# WARNING - Generated by {fusen} from dev/flat_paths_and_files.Rmd: do not edit by hand

#' RStudio only - Get exact path of the currently opened script
#' 
#' This function only works in RStudio and with an opened source document.  
#' There is exceptionnaly no example and exact test since these are running in background sessions in checks. 
#' 
#' @return Character 1L. A character vector indicating exact path of currently opened script
#' @export
#'
current_script_location <- function () {

  if (.Platform$GUI != "RStudio") {
    
    stop("This function is not working without RStudio")
  }
  
  dirname(
    path = rstudioapi::getSourceEditorContext()$path)
}
