# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

#' Inspect a collection of datasets
#'
#' @param input_path Character 1L. Folder path of datasets to explore
#' @param output_path Character 1L. Folder path where the exploration output will be stored
#' @param output_label Character 1L. Describe concisely the collection to explore
#' @param considered_extensions Character. Extensions of datasets retained for exploration
#' in the input folder. Do not type the "." (dot) in it. E.g ("parquet" but not ".parquet")
#' @return An excel file written on the computer containing exploration information
#' @examples
#' mydir <- tempdir()
#' dir.create(mydir)
#'
#' library(magrittr)
#' saveRDS(cars, file.path(mydir, "cars1.rds"))
#' saveRDS(mtcars, file.path(mydir, "cars2.rds"))
#'
#' # Code below illustrates how to use the function:
#' inspect_vars(input_path = mydir, output_path = mydir,
#'               output_label = "cardata", 
#'              considered_extensions = "rds")
#'
#'  purrr::map(1:10, \(x)
#'             rio::import(file.path(mydir, "inspect_vars_cardata.xlsx"),
#'                         sheet = x)) %>%
#'  magrittr::set_names(c("dims", "inspect_tot", "inspect_cars1", "inspect_cars2",
#'             "vars_detect", "vars_detect_everywhere", "vars_detect_not_everywhere",
#'             "vars_compclasses", "vars_compclasses_allsame", "vars_compclasses_not_allsame"))
#'             # code above illustrates all 10 sheets of the output
#'
#' unlink(mydir, recursive = TRUE)
#' @importFrom magrittr %>%
#' @importFrom stats nobs
#' @export
#'
inspect_vars <- function (input_path, output_path,
                          output_label, considered_extensions) {
  
  requireNamespace("magrittr")
  
  # Import datasets:
  # file extensions
  ext <- paste0("\\.", considered_extensions, "$") %>%
    paste0(collapse = "|")
  # files found in input folder
  lfiles <- list.files(input_path) %>%
    purrr::keep(stringr::str_detect(., ext))
  lfiles %>%
    # load each dataset
    purrr::map(\(x) {
      
      assign_to_global(x,
             rio::import(file.path(input_path, x),
                         encoding = "latin1"))
      invisible()
    })
  
  # Compute all datasets inspection as R objects:
  lfiles %>% purrr::map(\(x) {
    data <- get(x)
    inspect <- inspect(data)
    inspect <- inspect %>%
      (\(i) rbind(c("Obs = ", nrow(data),
                    rep("", ncol(i) - 1)),
                  c("Nvars = ", nrow(i),
                    rep("", ncol(i) - 1)),
                  cbind(1:nrow(i), i)))
    assign_to_global(paste0("inspect_", x), inspect)
    invisible()
  })
  
  # Datasets dimensions:
  dims <-
    paste0("inspect_", lfiles) %>%
    (\(l)
     purrr::map(l, get) %>%
       purrr::map(\(x) x[1:2, 2] %>% t %>%
                    as.numeric) %>% magrittr::set_names(l) %>%
       do.call(what = rbind)) %>%
    magrittr::set_colnames(c("nobs", "nvar")) %>%
    as.data.frame() %>%
    tibble::rownames_to_column(var = "datasets") %>%
    dplyr::mutate(datasets = stringr::str_remove(datasets, "inspect\\_") %>%
                    stringr::str_remove(paste0(".", considered_extensions) %>%
                                          paste(collapse = "|")))
  
  # Bind all inspection outputs:
  inspect_tot <-
    paste0("inspect_", lfiles) %>%
    (\(l)
     purrr::map(l, function (x) get(x)[- c(1:2), - 1] %>%
                  dplyr::mutate(datasets = x) %>% dplyr::relocate(datasets))) %>%
    do.call(what = rbind) %>%
    dplyr::mutate(datasets = stringr::str_remove(datasets, "inspect\\_") %>%
                    stringr::str_remove(paste0(".", considered_extensions) %>%
                                          paste(collapse = "|"))) %>%
    dplyr::left_join(dims, by = "datasets") %>%
    dplyr::relocate(nvar, nobs, .after = datasets)
  
  
  # Compute outputs of variable detection and type comparison above:
  vars_detect_data <- vars_detect(lfiles)
  vars_detect_everywhere_data <-
    vars_detect_everywhere(vars_detect_data)
  vars_detect_not_everywhere_data <-
    vars_detect_not_everywhere(vars_detect_data)
  vars_compclasses_data <- vars_compclasses(lfiles)
  # Same order as vars_detect:
  # (source :
  # https://stackoverflow.com/questions/27362718/reordering-rows-in-a-dataframe-
  # according-to-the-order-of-rows-in-another-datafra)
  vars_compclasses_data <- vars_compclasses_data %>%
    (\(d) d[order(match(vars_compclasses_data$vars_union,
                        vars_detect_data$vars_union)), ])
  vars_compclasses_allsame_data <-
    vars_compclasses_allsame(vars_compclasses_data)
  vars_compclasses_not_allsame_data <-
    vars_compclasses_not_allsame(vars_compclasses_data)
  
  # Write all outputs in an Excel file:
  writexl::write_xlsx(
    list(
      list("dims" = dims),
      list("inspect_tot" = inspect_tot),
      paste0("inspect_", lfiles) %>%
        (\(l) purrr::map(l, get) %>%
           magrittr::set_names(l %>%
                                 stringr::str_remove("inspect\\_") %>%
                                 (\(s)
                                  stringr::str_remove(s, paste0("\\.",
                                                                tools::file_ext(s)))))),
      list("vars_detect" = vars_detect_data),
      list("vars_detect_everywhere" = vars_detect_everywhere_data),
      list("vars_detect_not_everywhere" = vars_detect_not_everywhere_data),
      list("vars_compclasses" = vars_compclasses_data),
      list("vars_compclasses_allsame" = vars_compclasses_allsame_data),
      list("vars_compclasses_not_allsame" = vars_compclasses_not_allsame_data)
    ) %>% purrr::flatten(),
    file.path(output_path, paste0("inspect_vars_", output_label, ".xlsx"))
  )
  
  # Remove intermediate outputs in Global Environment to lighten the user:
  rm(list = ls(envir = globalenv()) %>%
       (\(ls)
        ls[ls %in%
             c(lfiles, paste0("inspect_", lfiles))]),
     envir = globalenv())
}
