# WARNING - Generated by {fusen} from dev/flat_inspect_variants.Rmd: do not edit by hand

#' Inspect a data frame and write the output in an excel file
#'
#' @param data_frame_name Character vector.
#' The data.frame to explore. Need to exist in the Global Environment
#' @param output_path Folder path where to write the excel output
#' @param output_label Optional 1-length character vector to label output file.
#' If NULL, data_frame_name will also used as label
#' @return Variable list of the dataset and systematic informations for each variable
#' @importFrom magrittr %>%
#' @export
#'
#' @examples
#' library(magrittr)
#' data(cars)
#' mydir <- tempdir()
#' dir.create(mydir)
#' inspect_write(data_frame_name = "cars", 
#'               output_path = mydir, 
#'               output_label = "cars")
#' readxl::read_xlsx(file.path(mydir, "inspect_cars.xlsx"))
#' unlink(mydir, recursive = TRUE)
inspect_write <- function (data_frame_name, output_path, output_label = NULL) {

  requireNamespace("magrittr")
  
  if (isFALSE(data_frame_name %in% ls(envir = globalenv()))) {
    
    stop("data_frame_name must exists in the global environment")
  }
  
  if (isFALSE(is.data.frame(get(data_frame_name)))) {
    
    stop(glue::glue("data_frame_name : {data_frame_name} must be of class data.frame"))
  }
  
  if (isFALSE(dir.exists(output_path))) {
    
    stop("output_path doesn't exist. Check validity")
  }

  if (is.null(output_label)) {

    name <- data_frame_name
  } else {

    name <- output_label
  }

  df <- get(data_frame_name)

  writexl::write_xlsx(
    inspect(df) %>%
      (\(i)
        rbind(
          c("Obs = ", nrow(df),
            rep("", ncol(i) - 1)),
          c("Nvars = ", nrow(i),
            rep("", ncol(i) - 1)),
          cbind(1:nrow(i), i)
        )),
    file.path(output_path, paste0("inspect_", name, ".xlsx")))
}
