# WARNING - Generated by {fusen} from dev/flat_convert_r.Rmd: do not edit by hand

#' Create an excel mask compatible with the convert_r() function
#' @param output_path Folder path where the mask will be created
#' @param output_filename File name (with extension) of the mask
#' @export
#'
#' @examples
#' mydir <- tempdir()
#' dir.create(mydir)
#'
#' mask_convert_r(output_path = mydir)
#'
#' list.files(mydir)
#'
#' unlink(mydir, recursive = TRUE)
mask_convert_r <- function (output_path,
                            output_filename = "mask_convert_r.xlsx") {

  if (isFALSE(dir.exists(output_path))) {
    
    stop("output_path doesn't exist")
  }
  
  mask <- data.frame(folder_path = NA,
                     file = NA,
                     converted_file = NA,
                     to_convert = NA)

  writexl::write_xlsx(mask,
                      path = file.path(output_path,
                                       output_filename))
}
