# WARNING - Generated by {fusen} from dev/flat_paths_and_files.Rmd: do not edit by hand

#' Move through paths
#'
#' @param path_vector Character. Vector of paths with equal number of levels
#' @param path_separator Character 1L. Path separator 
#' (adapted to your OS for instance)
#' @param move Integer 1L. 
#' If move > 0, outputs path till specified level in move. 
#' If move < 0, remove the last specified level(s) in move.
#'
#' @return Character. Transformed vector of paths. 
#' @importFrom magrittr %>% 
#' @importFrom glue glue
#' @export
#'
#' @examples
#' pvector <- c(
#'   "level_1/level_2/level_3/file_1.ext", 
#'   "level_1/level_2/level_3/file_2.ext"
#' )
#'
#' path_move(path_vector = pvector, 
#'           path_separator = "/", 
#'           move = 1)
#'
#' path_move(path_vector = pvector, 
#'           path_separator = "/", 
#'           move = 2)
#'
#' path_move(path_vector = pvector, 
#'           path_separator = "/", 
#'           move = - 1)
#'
#' path_move(path_vector = pvector, 
#'           path_separator = "/", 
#'           move = - 2)
path_move <- function (path_vector, path_separator = "/", move) {
  
  if (isFALSE(is.character(path_vector))) {
    
    stop("path_vector must be a character vector")
  }
  
  if (isFALSE(is.numeric(move))) {
    
    stop("move must be a numeric")
  }
  
  if (isTRUE(move == 0)) {
    
    stop("move must be different from 0")
  }
  
  split <- strsplit(path_vector, path_separator)
  plevels <- purrr::map_dbl(split, length)
  
  if (isFALSE(length(rle(plevels)$values) == 1)) {
    
    df_error <- data.frame("path_vector" = path_vector, 
                           "number_of_levels" = plevels)
    
    print(df_error)
    
    stop("All path_vector elements must have the same number of levels")
  }
  
  pmatrix <- split %>% do.call(what = rbind)
  ncol <- ncol(pmatrix)
  move <- as.integer(move)
  
  if (move > 0) {
    
    if (isFALSE(move %in% 1:ncol)) {
      
      stop(glue::glue("level must be comprised between one of these values : {
                      paste(1:ncol, collapse = ', ')}"))
    }
    
    pmatrix[, 1:move, drop = FALSE] %>% 
      apply(1, \(x) 
            paste(x, collapse = path_separator))
    
  } else {
    
    if (isTRUE(abs(move) >= ncol(pmatrix))) {
      
      stop(glue::glue(
        "move absolute value must be strictly positive and strictly lesser than {ncol}"))
    }
    
    pmatrix[, - (ncol(pmatrix):(ncol(pmatrix) + move + 1)), drop = FALSE] %>% 
      apply(1, \(x) 
            paste(x, collapse = path_separator))
  }
}
