# WARNING - Generated by {fusen} from dev/flat_rename_r.Rmd: do not edit by hand

#' Industrialized file renaming
#' 
#' @param mask_filepath Character 1L. Entire file path of the excel mask
#'
#' @return See file renamed within the mask folder
#' 
#' @export
#' @examples
#' library(magrittr)
#' data(cars)
#' data(mtcars)
#'
#' mydir <- tempfile()
#' dir.create(mydir)
#'
#' # Two example files to rename: 
#' saveRDS(cars, file.path(mydir, "cars.rds"))
#' saveRDS(mtcars, file.path(mydir, "mtcars.rds"))
#' list.files(mydir)
#'
#' # Create the mask: 
#' mask_rename_r(input_path = mydir)
#'
#' # Fill the mask (in practice you can do it manually): 
#' mask <- rio::import(file.path(mydir, "mask_rename_r.xlsx"))
#' mask[["renamed_file"]] <- c("cars_renamed.rds", "mtcars_renamed.rds")
#' mask[["to_rename"]] <- rep(1, 2)
#' writexl::write_xlsx(mask, file.path(mydir, "mask_rename_r.xlsx"))
#'
#' # Apply the rename function: 
#' rename_r(mask_filepath = file.path(mydir, "mask_rename_r.xlsx"))
#'
#' # See the renamed files: 
#' list.files(mydir)
#'
#' # Clean tempdir: 
#' unlink(mydir, recursive = TRUE)
rename_r <- function(mask_filepath){
    
  if (! file.exists(mask_filepath)) {
    stop("mask_filepath doesn't exist. It must be a valid and full path including the xlsx file.")
  }
  
  prm <- rio::import(mask_filepath)
  
  if (! all(c("file", "renamed_file", "to_rename") %in% names(prm))) {
    stop("The mask must have the columns: file, renamed_file, to_rename")
  }
  
  prm <- prm[prm$to_rename == 1, ]
  prm[["row_number"]] <- 1:nrow(prm)
  
  sp <- split(prm, prm[["row_number"]])
  names(sp) <- paste0(basename(prm[["file"]]))
  
  purrr::map(sp, \(x) 
             file.rename(
               file.path(dirname(mask_filepath), x[["file"]]), 
               file.path(dirname(mask_filepath), x[["renamed_file"]])))
}
