# WARNING - Generated by {fusen} from dev/flat_replace_multiple.Rmd: do not edit by hand

# replace_multiple

#' Replace character vector values using a correspondence approach
#' @param input_vector Character. Character vector on which replacements take place
#' @param replacements Character. Named character vector: replacement correspondences
#' @param replace_all Logical. If TRUE, stringr::str_replace_all() is used
#' instead of stringr::str_replace()
#' @examples
#' input <- c("one-one", "two-two-one", "three-three-two")
#'
#' replace_multiple(input,
#'                  replacements =
#'                    c("one" = "1", "two" = "2",
#'                      "three" = "3"))
#'
#' replace_multiple(input,
#'                  replacements =
#'                    c("one" = "1", "two" = "2",
#'                      "three" = "3"),
#'                  replace_all = TRUE)
#' @importFrom magrittr %>%
#' @export
#'
replace_multiple <- function (input_vector, replacements,
                              replace_all = FALSE) {

  if (isFALSE(is.character(input_vector))) {
    
    stop("input_vector must be a character vector")
  }
  
  if (isFALSE(is.character(replacements))) {
    
    stop("replacements must be a character vector")
  }
  
  # if replace_all == TRUE, use str_replace_all instead of str_replace:
  replace_function <- function (...) {

    if (replace_all) stringr::str_replace_all(...)
    else stringr::str_replace(...)

  }

  input <- names(replacements)

  if (length(unique(input)) != length(input)) {
    stop("Original values must be unique in the `replacements` argument.")
  }

  output <- unname(replacements)

  replace_table <- data.frame(
    input, output
  )

  # replacement process:
  dplyr::tibble(input_vector = input_vector,
                origin =
                  stringr::str_extract(input_vector,
                                       input %>% paste(collapse = "|"))) %>%
    dplyr::left_join(replace_table, by = c("origin" = "input")) %>%
    dplyr::mutate(destination = replace_function(input_vector, origin, output)) %>%
    dplyr::pull(destination)
}
