# WARNING - Generated by {fusen} from dev/flat_importations.Rmd: do not edit by hand

#' Import a collection of datasets into the Global Environment (serialized)
#' @param file_paths Character. Vector of valid absolute file paths of
#' datasets to import
#' @return After completion, see the datasets imported in the Global Environment
#' @importFrom magrittr %>%
#' @export
#'
#' @examples
#' library(magrittr)
#' mydir <- system.file("permadir_examples_and_tests/importations", package = "industtry")
#' lfiles <- list.files(mydir, full.names = TRUE) %>% 
#'   (\(x) x[stringr::str_detect(x, "\\.rds$")])
#'
#' # Launch this code and check your global env, 
#' # cars.rds and mtcars.rds should be there: 
#' serial_import(lfiles)
serial_import <- function (file_paths) {
  
  if (isFALSE(all(file.exists(file_paths)))) {
    
    noexist <- file_paths[! file.exists(file_paths)]
    print("These file_paths doesn't exist; check again: ")
    print(noexist)
    stop("All file_paths must be valid")
  }
  
  if (isFALSE(length(unique(basename(file_paths))) == length(file_paths))) {
    
    duplnames <- basename(file_paths)[duplicated(basename(file_paths))]
    print("These file names are duplicated at least once: ")
    print(duplnames)
    stop("File names must be unique")
  }
  
  # For each absolute file path inputted, launch a background job that
  # imports the data set mentioned in the corresponding path;
  # the R object being the file name itself:
  
  purrr::map(file_paths,
             \(x) {
               
               assign_to_global(basename(x),
                      rio::import(x))
               invisible()
             })
}
