# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

#' Collection-level variables types comparison
#'
#' @param data_frames The datasets to explore. Need to exist in the Global Environment
#' @return Variable list and their respective types across all inputted datasets.
#' @examples
#' library(magrittr)
#' data(cars)
#' data(mtcars)
#' vars_compclasses(c("cars", "mtcars"))
#' @importFrom magrittr %>%
#' @export
#'
vars_compclasses <- function (data_frames) {
  
  requireNamespace("magrittr")
  
  vars_union <- purrr::map(data_frames, get) %>%
    purrr::map(names) %>% unlist %>% unique
  data_frames %>% (\(ll) purrr::map(ll, \(x) {
    g <- get(x)
    purrr::map(vars_union,
               \(y)
               ifelse(ncol(g) > 0, class(g[[y]]) %>%
                        # avoid problems with 2L class variables:
                        paste(collapse = "/"), NULL) %>%
                 stringr::str_replace("NULL$", "-")) %>%
      do.call(what = rbind)}) %>%
      do.call(what = cbind) %>%
      magrittr::set_rownames(vars_union) %>%
      magrittr::set_colnames(ll)) %>%
    as.data.frame %>%
    tibble::rownames_to_column() %>%
    (\(d) {
      names(d)[1] <- "vars_union"
      d
    })
}
