# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

#' Variable class comparison - all of same type across all datasets
#'
#' @param vars_compclasses_table Output of the vars_compclasses() function in this package.
#' @return From vars_compclasses_table, extract type-consistent variables through all the datasets.
#' @examples
#' library(magrittr)
#' vcompclasses_table <- vars_compclasses(c("cars", "mtcars"))
#' vars_compclasses_allsame(vcompclasses_table)
#' library(magrittr)
#' data(cars)
#' data(mtcars)
#' vcompclasses <- vars_compclasses(c("cars", "mtcars"))
#' vars_compclasses_allsame(vcompclasses)
#' @importFrom magrittr %>%
#' @export
#'
vars_compclasses_allsame <- function (vars_compclasses_table) {
  
  requireNamespace("magrittr")
  
  vars_compclasses_table %>% (\(d) {
    allsame <- apply(d, 1, function (x)
      length(unique(x[-1] %>%
                      (\(xx)
                       xx[xx != "-"]))) == 1) %>% unlist
    d[allsame,]
  })
}
