# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

#' Variable detection patterns
#'
#' @param data_frames The datasets to explore. Need to exist in the Global Environment
#' @return Variable list and indicators of presences/absences across all inputted datasets.
#' @examples
#' library(magrittr)
#' data(cars)
#' data(mtcars)
#' vars_detect(c("cars", "mtcars"))
#' @importFrom magrittr %>%
#' @export
#'
vars_detect <- function (data_frames) {
  
  requireNamespace("magrittr")
  
  if (isFALSE(all(data_frames %in% ls(envir = globalenv())))) {
    
    stop("data_frames must be a vector of object names that exist in the global environment")
  }
  
  # Warnings here are mechanical and not harmful nor falsifying: 
  suppressWarnings({
    out_data <- data_frames %>%
      purrr::map(\(x) get(x) %>% names %>% as.data.frame %>%
                   magrittr::set_names(x) %>% (\(x2) cbind(x2, x2) %>%
                                                 (\(c) {
                                                   colnames(c)[1] <- "union"
                                                   c
                                                 }))) %>%
      (\(l)
       plyr::join_all(list(as.data.frame(unique(unlist(l))),
                           l %>% purrr::map(as.data.frame)) %>%
                        purrr::flatten() %>%
                        (\(l2) {
                          l2[[1]] <- as.data.frame(l2[[1]]) %>%
                            magrittr::set_names("union")
                          l2
                        }), type = "left")) %>%
      (\(d) {
        cbind(d[, 1],
              dplyr::mutate_all(d[, 2:ncol(d)],
                                \(x) ifelse(! is.na(x), "ok", "-"))) %>%
          (\(d2) {names(d2)[1] <- "vars_union" ; d2})
      })
    
    # Arrange lines to better visualize presence/absence patterns.
    # Critrias: rkfirst_ok, desc(nb_ok_conseq), desc(rkfirst_out),
    # desc(nb_out_conseq):
    
    rkfirst_ok <- out_data[, - 1] %>%
      apply(1, \(x) min(which(x == "ok")))
    
    nb_ok_conseq <- out_data %>%
      apply(1, \(x) rle(as.numeric(x == "ok"))$lengths[2])
    
    rkfirst_out <- out_data[, - 1] %>%
      apply(1, \(x) min(which(x == "-")))
    
    nb_out_conseq <- out_data %>%
      apply(1, \(x) rle(as.numeric(x == "-"))$lengths[2])
    
    out_data <- dplyr::mutate(out_data,
                              rkfirst_ok, nb_ok_conseq,
                              rkfirst_out, nb_out_conseq)
    
    dplyr::arrange(out_data,
                   rkfirst_ok, dplyr::desc(nb_ok_conseq),
                   dplyr::desc(rkfirst_out), dplyr::desc(nb_out_conseq)) %>%
      dplyr::select(- rkfirst_ok, - nb_ok_conseq,
                    - rkfirst_out, - nb_out_conseq)
  })
}
