# WARNING - Generated by {fusen} from dev/flat_inspect_vars.Rmd: do not edit by hand

#' Variable detection - presence across all the datasets
#'
#' @param vars_detect_table Output of the vars_detect() function in this package.
#' This object must exists into the Global Environment.
#' @return From vars_detect_table, extract variables that are always present through all the datasets.
#' @examples
#' library(magrittr)
#' library(dplyr)
#' data(cars)
#' data(mtcars)
#' vdetect_table <- vars_detect(c("cars", "mtcars"))
#' vars_detect_everywhere(vdetect_table)
#' @importFrom magrittr %>%
#' @export
#'
vars_detect_everywhere <- function (vars_detect_table) {
  
  requireNamespace("magrittr")
  
  vars_detect_table %>% (function (d) {
    
    everywhere <-
      apply(d, 1,
            \(x) identical(unique(x[-1]), "ok")) %>% unlist
    
    d[everywhere, ]
    
  })
}
